version: '1'
name: lnmp
services:
  nginx:
    image: 'nginx:stable'
    privileged: true
    volumes:
      - ./etc/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./etc/nginx/cert:/etc/nginx/cert:ro
      - ./var/log/nginx:/var/log/nginx:rw
      - ./data/www:/usr/share/nginx/html:rw
    depends_on:
      - php
    networks:
      - dev
    restart: always
    environment:
      - TZ=Asia/Shanghai
    ports:
      - "80:80"
      - "443:443"
 
  php:
    image: 'php:my-7.4-fpm'
    privileged: true
    volumes:
      - ./etc/php/php.ini:/usr/local/etc/php/php.ini:ro
      - ./etc/php/php-fpm.conf:/usr/local/etc/php-fpm.conf:ro
      - ./etc/php/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro
      - ./var/log/php:/var/log/php:rw
      - ./data/www:/www:rw
    external_links:
      - skywalking-oap-server:skywalking-oap
    networks:
      - dev
    restart: always
    environment:
      - TZ=Asia/Shanghai
 
#networks:
#  dev:
#    external: true
