version: '1'
name: storage

services:
  mysql:
    image: 'mysql:8'
    privileged: true
    volumes:
      - ./data/mysql:/var/lib/mysql:rw
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    networks:
      - dev
    ports:
      - "3306:3306"
    restart: always
    
  redis:
    image: 'redis:6'
    privileged: true
    volumes:
      - ./etc/redis/redis.conf:/usr/local/etc/redis/redis.conf:ro
      - ./data/redis/:/data:rw
    networks:
      - dev
    restart: always
    environment:
      - TZ=Asia/Shanghai
    ports:
      - "6379:6379"
    command: ["redis-server","/usr/local/etc/redis/redis.conf"]

networks:
  dev:
    external: true
