version: '1'
services:
  nginx:
    image: 'nginx:stable'
    privileged: true
    volumes:
        - D:\workspace\leidawaimai.com:/usr/share/nginx/html/ldwm:rw
        - D:\workspace\nginx\conf.d:/etc/nginx/conf.d:rw
        - D:\workspace\nginx\log:/var/log/nginx:rw
    depends_on:
        - phalcon
    networks:
        dev:
            ipv4_address: 172.32.0.3
    restart: always
    environment:
        - TZ=Asia/Shanghai
    ports:
        - "80:80"
 
  phalcon:
    image: 'php7.3-fpm:phalcon'    
    privileged: true
    volumes:
        - D:\workspace\leidawaimai.com:/www/ldwm:rw
        - D:\workspace\leidawaimai.com\storage:/www/ldwm/storage:rw
        - D:\workspace\php\etc\php.ini:/usr/local/etc/php/php.ini:ro
    networks:
        dev:
            ipv4_address: 172.32.0.2
    restart: always
    environment:
        - TZ=Asia/Shanghai
        
  
  redis:
    image: 'redis:6'
    privileged: true
    volumes:
        - D:\workspace\redis\redis.conf:/usr/local/etc/redis/redis.conf:ro
    networks:
        dev:
            ipv4_address: 172.32.0.4
    restart: always
    environment:
        - TZ=Asia/Shanghai
    ports:
        - "6379:6379"
    command: ["redis-server","/usr/local/etc/redis/redis.conf"]
 
networks:
  dev:
    ipam:
      config:
        - subnet: 172.32.0.0/24