version: '1'
name: phpenv
services:
  nginx:
    image: 'nginx:stable'
    privileged: true
    volumes:
      - $CONFIG_DIR/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - $CONFIG_DIR/nginx/conf.d:/etc/nginx/conf.d:ro
      - $LOG_DIR/nginx:/var/log/nginx:rw
      - $WORKSPACE_DIR/www:/www:rw
    depends_on:
      - php7
      - php8
    networks:
      - dev
    restart: always
    environment:
      - TZ=Asia/Shanghai
 
  php7:
    image: 'php:my-7.4-fpm'
    privileged: true
    volumes:
      - $CONFIG_DIR/php/7/php.ini:/usr/local/etc/php/php.ini:ro
      - $CONFIG_DIR/php/7/php-fpm.conf:/usr/local/etc/php-fpm.conf:ro
      - $CONFIG_DIR/php/7/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro
      - $LOG_DIR/php/7:/var/log/php:rw
      - $WORKSPACE_DIR/www:/www:rw
    external_links:
      - skywalking-oap-server-1:skywalking-oap
      - storage-redis-1:redis
      - storage-mysql-1:mysql
    networks:
      - dev
    restart: always
    environment:
      - TZ=Asia/Shanghai

  php8:
    image: 'php:my-8.2-fpm'
    privileged: true
    volumes:
      - $CONFIG_DIR/php/8/php.ini:/usr/local/etc/php/php.ini:ro
      - $CONFIG_DIR/php/8/php-fpm.conf:/usr/local/etc/php-fpm.conf:ro
      - $CONFIG_DIR/php/8/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro
      - $LOG_DIR/php/8:/var/log/php:rw
      - $WORKSPACE_DIR/www:/www:rw
    external_links:
      - storage-redis-1:redis
      - storage-mysql-1:mysql
    networks:
      - dev
    restart: always
    environment:
      - TZ=Asia/Shanghai
 
networks:
  dev:
    external: true
