version: '1'
name: storage

services:
  mysql:
    image: 'mysql:latest'
    privileged: true
    deploy: 
      mode: global
    volumes:
      - $CONFIG_DIR/mysql:/etc/mysql/conf.d:ro
      - $DATA_DIR/mysql:/var/lib/mysql:rw
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
    ports:
      - "3306:3306"
    restart: always
    
  redis:
    image: 'redis:6-with-plugin'
    build:
      context: "../dockerfiles/"
      dockerfile: "redis-dockerfile"
    privileged: true
    deploy: 
      mode: global
    volumes:
      - $CONFIG_DIR/redis/redis.conf:/usr/local/etc/redis/redis.conf:ro
      - $DATA_DIR/redis/:/data:rw
    restart: always
    environment:
      - TZ=Asia/Shanghai
    ports:
      - "6379:6379"
    command: ["redis-server","/usr/local/etc/redis/redis.conf","--requirepass",$REDIS_REQUIREPASS]

networks:
  default:
     external:
       name: ${DOCKER_NETWORK_NAME}
